
package proyectooo1.vistas;
import proyectooo1.clases.*;
import javax.swing.JOptionPane;

public class Iniciosesion extends javax.swing.JFrame {
        Admin admin ;
        Administrador administrador;
        
    public Iniciosesion() {
       
        this.admin = new Admin("admin", "admin");
        this.administrador=new Administrador();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        JLcodigo = new javax.swing.JLabel();
        JLcontraseña = new javax.swing.JLabel();
        Btninicio = new javax.swing.JButton();
        Txtcodigo = new javax.swing.JTextField();
        txtcontraseña = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DTT");

        JLcodigo.setText("CODIGO");

        JLcontraseña.setText("CONTRAESEÑA");

        Btninicio.setText("INICIAR SESION");
        Btninicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtninicioActionPerformed(evt);
            }
        });

        Txtcodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtcodigoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(179, Short.MAX_VALUE)
                .addComponent(Btninicio, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(171, 171, 171))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLcontraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Txtcodigo)
                    .addComponent(txtcontraseña, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))
                .addGap(63, 63, 63))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLcontraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcontraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(84, 84, 84)
                .addComponent(Btninicio, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtninicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtninicioActionPerformed
     String codigoQuemadoAdmin = "admin";
    String contraseñaQuemadaAdmin = "admin";
    String usuarioIngresado = Txtcodigo.getText();
    String contrasenaIngresada = new String(txtcontraseña.getPassword());

    try {
        if (usuarioIngresado.isEmpty() || contrasenaIngresada.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos.");
        } else {
            if (codigoQuemadoAdmin.equals(usuarioIngresado) && contraseñaQuemadaAdmin.equals(contrasenaIngresada)) {
                // Inicio de sesión para el administrador
                JOptionPane.showMessageDialog(this, "Bienvenido, administrador");
                this.administrador.setVisible(true);
                this.setVisible(false);
            } else {
                // No es el administrador, verificamos si es un profesor
                boolean profesorEncontrado = false;
                for (Profesor profesor : Admin.getprofesores()) {
                    if (profesor.getCodigo() == Integer.parseInt(usuarioIngresado) && profesor.getPassword().equals(contrasenaIngresada)) {
                        // Credenciales válidas para un profesor
                        profesorEncontrado = true;
                        JOptionPane.showMessageDialog(this, "Bienvenido, profesor " + profesor.getNombre());
                        this.dispose();
                        VistaProfesor vistap = new VistaProfesor();
                        vistap.setVisible(true);
                        break; // Salir del bucle si se encuentra un profesor válido
                    }
                }

                if (!profesorEncontrado) {
                    // No es el administrador ni un profesor, verificamos si es un usuario
                    boolean usuarioEncontrado = false;
                    for (Alumno alumno : Admin.getAlumnos()) {
                        if (alumno.getCodigo() == Integer.parseInt(usuarioIngresado) && alumno.getPassword().equals(contrasenaIngresada)) {
                            // Credenciales válidas para un usuario
                            usuarioEncontrado = true;
                            JOptionPane.showMessageDialog(this, "Bienvenido, alumno " + alumno.getNombre());
                            this.dispose();
                            VistaAlumno vistaa = new VistaAlumno();
                            vistaa.setVisible(true);
                            break; // Salir del bucle si se encuentra un usuario válido
                        }
                    }

                    if (!usuarioEncontrado) {
                        // Contraseña o usuario incorrectos
                        JOptionPane.showMessageDialog(this, "Contraseña o usuario incorrectos");
                    }
                }
            }
        }
    } catch (NumberFormatException e) {
        // Captura la excepción de tipo NumberFormatException
        JOptionPane.showMessageDialog(this, "El código de usuario debe ser un número entero");
    }
    }//GEN-LAST:event_BtninicioActionPerformed

    private void TxtcodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtcodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtcodigoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Iniciosesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Iniciosesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Iniciosesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Iniciosesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Iniciosesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btninicio;
    private javax.swing.JLabel JLcodigo;
    private javax.swing.JLabel JLcontraseña;
    private javax.swing.JTextField Txtcodigo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txtcontraseña;
    // End of variables declaration//GEN-END:variables
}
